export async function downloadOutfitReport(outfit: any, weather: any, location: string) {
  // Create a simple HTML report
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Outfit Report - ${new Date().toLocaleDateString()}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; background: #faf9f7; }
    .header { text-align: center; margin-bottom: 30px; }
    .header h1 { color: #e67e50; margin: 0; }
    .weather-info { background: white; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
    .items { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }
    .item { background: white; padding: 15px; border-radius: 8px; text-align: center; }
    .item img { width: 100%; height: 200px; object-fit: cover; border-radius: 4px; margin-bottom: 10px; }
    .item-name { font-weight: bold; margin-bottom: 5px; }
    .item-details { font-size: 12px; color: #666; }
    .style-notes { background: white; padding: 15px; border-radius: 8px; margin-top: 20px; }
    .footer { text-align: center; margin-top: 30px; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🌤️ Weather Smart Outfit Report</h1>
    <p>${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
  </div>
  
  <div class="weather-info">
    <h3>📍 ${location}</h3>
    <p><strong>Temperature:</strong> ${weather?.temperature}°F</p>
    <p><strong>Condition:</strong> ${weather?.condition || 'N/A'}</p>
    <p><strong>Humidity:</strong> ${weather?.humidity}%</p>
  </div>
  
  <h2>Your Outfit</h2>
  <div class="items">
    ${outfit?.items?.map((item: any) => `
      <div class="item">
        ${item.image ? `<img src="${item.image}" alt="${item.name}">` : '<div style="height: 200px; background: #f0f0f0; display: flex; align-items: center; justify-content: center; border-radius: 4px;">No Image</div>'}
        <div class="item-name">${item.name}</div>
        <div class="item-details">
          ${item.category ? `<div>Category: ${item.category}</div>` : ''}
          ${item.color ? `<div>Color: ${item.color}</div>` : ''}
        </div>
      </div>
    `).join('') || '<p>No items</p>'}
  </div>
  
  ${outfit?.style_notes ? `
    <div class="style-notes">
      <h3>💡 Style Notes</h3>
      <p>${outfit.style_notes}</p>
    </div>
  ` : ''}
  
  ${outfit?.colorHarmony ? `
    <div class="style-notes">
      <h3>🎨 Color Harmony</h3>
      <p><strong>${outfit.colorHarmony.harmonyType}</strong></p>
      <p>${outfit.colorHarmony.explanation}</p>
    </div>
  ` : ''}
  
  <div class="footer">
    <p>Generated by Weather Smart • AI-Powered Outfit Recommendations</p>
  </div>
</body>
</html>
  `
  
  // Create blob and download
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `outfit-report-${new Date().toISOString().split('T')[0]}.html`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
